### ISSUE TITLE
Joomla 3.3.1 Version Formating issue in the Admin screens

### ISSUE THREAD

**Issue by daveplays** [BabDev/Podcast-Manager#189]
Hello,

Great extension. I see a problem with the formatting in the Joomla 3.3.1 backend system. I know they made a bunch of changes to the why they display. Is there a easy fix. I am using a rocket template.

I attached screen grabs. It is something about the tabs not working. I tried the 2.1.0 and the 2.1.0rc versions. Same thing. 

Ideas? Thanks so much.

![0001](https://cloud.githubusercontent.com/assets/9471742/4854226/27470ed0-608f-11e4-8eb6-fa08daeaeff8.JPG)
![0002](https://cloud.githubusercontent.com/assets/9471742/4854227/2749bedc-608f-11e4-97e1-b6cc8181d78a.JPG)
![0003](https://cloud.githubusercontent.com/assets/9471742/4854228/2750f580-608f-11e4-9e9e-487ec21d6b9d.JPG)

**Comment by mbabker** [comment]
Did you get anywhere with this by chance?  Also, I missed it in the original report, but you mentioned using a "rocket template".  Is this for the backend?  If that's the case, because of how I have the layout code written, the optimized Joomla 3 layouts aren't being installed for that template (it's coded to use Joomla's layout override system to override the layouts for the Isis template while the default layouts are the 2.5 version).

**Comment by daveplays** [comment]
Hello Michael,

Thanks for getting back to me.

I still am having the problem. I added some custom CSS to help make it
usable. But it is not ideal.

I am using Joomla! 3.3.1 Stable [ Ember ] 11-June-2014 13:30 GMT

and Racket theme template. So you joomla 3 layouts aren't being installed
for that tempate. Is there something I can do to correct that? Are you
working on an update. Other modules seam to handle this.

I have not made many complete modules so I am not sure how to fix it. But
if I can help get you module working better I would love that becuase I can
see using it for other clients I have.

Let me know what you need. I can give you access if you need it.

Thanks

Peace,
David

**Comment by mbabker** [comment]
There is a solution but it will take a little work on your part.

In the 2.1.0 release package, when you unzip it there is a folder named `strapped`; this folder has all of the Isis layout overrides.  You could copy those layouts into the correct place so that they are used as the default layouts.  Using this an example to describe how this whole process would work:

Within the strapped folder is the path `com_podcastmanager/cpanel/default.php`.  This is the override for the default layout in the cpanel view; you would copy this file to `administrator/components/com_podcastmanager/views/cpanel/tmpl/default.php`.  The same logic then applies to all of the .php files in the folder (the language folder, index.html files and the XML file can be ignored this way).  So `com_podcastmedia/audiolist/default_folder.php` would be copied to `administrator/components/com_podcastmedia/views/audiolist/tmpl/default_folder.php`.

My trick for Joomla 2.5 & 3 support was to keep the 2.5 based layouts as the default layouts while using template overrides for Joomla 3's Isis template.  Unfortunately this isn't a fool-proof solution in the case of third party templates, as you've run into here.  Luckily, the upcoming 2.2 release is the last to support both 2.5 and 3 so it won't be an issue for much longer.

One thing I can consider is reworking how the layouts are put in place.  Instead of using overrides, I could possibly just copy the files into the main component as the default layouts for Joomla 3.

**Comment by mbabker** [comment]
Closing this.  With the 3.0 updates the layout complexity goes away.
