### ISSUE TITLE
Bad http result code: 500 on iTunes

### ISSUE THREAD

**Issue by blutch** [BabDev/Podcast-Manager#213]
Hi, i have a problem with adding my feed in itunes podcasts. My feed is http://www.radiocristal.org/component/podcastmanager/?format=raw&feedname=2, iTunes ansewrs "Bad http result code: 500"
How to fix it ?
thank you for your help !

**Comment by mbabker** [comment]
Since the feed is accessible normally and through tools like curl, I'd suggest that the way iTunes is trying to pull the feed is getting blocked by your server or raising an error.  Check your server error logs to see if there's something with more data or contact iTunes support to see if they can give you more information.

**Comment by blutch** [comment]
when i click on itpc://www.radiocristal.org/les-podcasts/podcasts-info-energie.raw?feedname=2, it add the feed on my itunes, but not in the itunes store

**Comment by mbabker** [comment]
That reaffirms that there is an issue communicating between iTunes and your site somewhere.  All the troubleshooting steps I know from past experiences have shown zero issues with loading the feed, and without anymore detail (a HTTP 500 code is the web's version of taking your vehicle to the mechanic and saying "it's broken but I don't know why"), it's hard to really dig any further.
