### ISSUE TITLE
Feeds not updating iTunes, Can't parse your feed

### ISSUE THREAD

**Issue by bwflinn** [BabDev/Podcast-Manager#223]
Using 2.2.0 with Joomla 3.4.8

All of our feeds stopped updating on iTunes on Feb 2nd 2016

So I checked the feeds out on podcastsconnectapple.com and all are giving this error:

Can’t parse your feed. Invalid XML: Error on line 2: The processing instruction target matching "[xX][mM][lL]" is not allowed.

Here is a link to one of our feeds:
http://sports56whbq.com/index.php/component/podcastmanager/?format=raw&feedname=11

FeedValidator.org says:
line 2, column 0: XML parsing error: <unknown>:2:0: XML or text declaration not at start of entity

**Comment by mbabker** [comment]
There is an extra white space line at the start of the feeds, meaning something (another plugin perhaps?) is sending an output before the feed XML gets echoed out.  Try turning on error reporting and see if there are any errors, otherwise I'd suggest start disabling third party content and system plugins one by one until you find a culprit.  If this fixes it, usually it's an indicator that the plugin isn't doing proper environmental checks and tries to run when it shouldn't.

**Comment by bwflinn** [comment]
That was it!  Thanks!!! I disabled a few plugins we were trying out and that fixed it.  I refreshed the feeds in iTunes and everything is updating current again.  Thank you.
