### ISSUE TITLE
Space before the <?xml> tag

### ISSUE THREAD

**Issue by ali-souissi2003** [BabDev/Podcast-Manager#237]
Feed not validating beacause it was a space before the <?xml> tag
Version:  2.2.0
Joomla Version: 3.1.5
Feed link: http://thd.tn/index.php?option=com_podcastmanager&format=raw&feedname=1

**Comment by mbabker** [comment]
1) Please update your Joomla version ASAP; there are numerous high level security vulnerabilities that have been patched since August 2013.

2) This isn't an issue with the component.  This is another plugin on your site incorrectly adding output to the document when the document is not Joomla's default HTML type.  Enable error reporting on your site in case there are any PHP errors happening in the background and start disabling plugins one-by-one that have IDs greater than 10000 until you find the culprit (usually it's a content or system plugin that's at fault).
